### ISSUE TITLE
TechEmpower - FrameworkBenchmarks

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simd-json#122]
It might be worth considering adding simd-json to the TechEmpower benchmarks:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/cfbbf5d11143c96851620eb1aeaf3c2893e862c9/frameworks/Rust/actix/src/main.rs#L23

To make this really worthwhile #121 would be good.

suggested by @pickfire

**Comment by fafhrd91** [comment]
I'll change tfb benchmarks.

**Comment by Licenser** [comment]
👍 note that the simd-json-derive is still extremely experimental but it should work :tm:

**Comment by fafhrd91** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/pull/5613

**Comment by pickfire** [comment]
Looking at the performance from visualization of json serialization, there seemed to be a tiny drop in performance but not significant.

Before https://www.techempower.com/benchmarks/#section=test&runid=8dca2265-62dc-4532-854b-9959afe18652&hw=ph&test=json
After https://www.techempower.com/benchmarks/#section=test&runid=832828ba-3e18-415d-b492-461260ddc510&hw=ph&test=json

But I am surprised may-minihttp is much faster in the list, this may be due to their plain router implementation but I am not sure about that.

**Comment by Licenser** [comment]
I think that's within measuring tolerance, and not surprising that there is virtually no difference the struct that gets serialized is quite small so the benefit of simd-accelerated string decoding (especially since no data needs any utf8 encoding) is neglectable.

What'd be an interesting next step is switching to https://github.com/simd-lite/simd-json-derive for serialization instead of serde-derive that might actually make a bigger dent then just switching from serde-json to simd-json for serialisation

**Comment by fafhrd91** [comment]
it already uses simd-json-derive, https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/actix/src/main.rs#L14

**Comment by Licenser** [comment]
Interesting, I expected a bigger difference, but then again it's a fairly small payload.

**Comment by pickfire** [comment]
@fafhrd91 Is serialization taking up even 1% of the cpu time for the techempower benchmarks?

**Comment by fafhrd91** [comment]
I don't know about cpu usage, I've never measured.
