### ISSUE TITLE
What is the behaviour of the fallback mode ?

### ISSUE THREAD

**Issue by dvtkrlbs** [simd-lite/simd-json#134]
What exactly does this crate do in fallback mode ?

**Comment by Licenser** [comment]
Normally we forbid compiling for targets that do not support SSE4.2 or AVX2 instructions. Using fallback disables those checks and allows rust to use software variants of the instructions in questions.

Using software standings is more compatible but significantly slower, to the degree that good rust code such as json-rs or serde_json outperform it.

The main reason for the fallback mode is if simd-json is pulled in as a sub-dependency of a library and JSON isn't of much importance for the project itself (i.e. it's only used to read a config file) and bothering with build targets is too much work.

I hope I could explain this good enough?

**Comment by dvtkrlbs** [comment]
Yeah that explains it thank you. Also any plans to add a fallback mode to serde_json. I recently added simd-json support to a library and it is really cumbersome to do it. Also the fact that from_slice requires a mutable reference (i understand why) is annoying.

**Comment by Licenser** [comment]
There are currently no plans for that, no but off the top of my head I can't think of a reason why this can't be done, it, however, pulls in the serde dependencies and we're in the process to move further away from them with own derive-traits to reduce the dependency graph and improve performance for those. That said since it'd be feature-gated anyway that's probably fine :).

If you got a link to the commits for adding simd-json I'd be really curious to take a look and see where the friction is, perhaps we can improve the API to make it less painful. However, I don't see the `&mut` going away with a more pleasant API. I've been thinking about that a bit, as I know it sucks, and the only alternative I can think of is to pass in a secondary owned buffer that is then returned to store strings (similarly how upstream simdjson handles it) but I feel like that would make the API less not more friendly.

**Comment by dvtkrlbs** [comment]
[Here](https://github.com/twilight-rs/twilight/pull/182/commits/3aa0548eb15a63eba918a6cde605e93c1c83b62b) is the relevant commit. It is not the final version.

**Comment by Licenser** [comment]
Non tested idea:

Instead of (same for from_str)
```rust
#[cfg(all(feature = "serde_json", not(feature = "simd-json")))]
pub(crate) use serde_json::from_slice as json_from_slice;
#[cfg(feature = "simd-json")]
pub(crate) use simd_json::from_slice as json_from_slice;
#[cfg(all(feature = "serde_json", not(feature = "simd-json")))]
pub(crate) use serde_json::from_str as json_from_str;
#[cfg(feature = "simd-json")]
pub(crate) use simd_json::from_str as json_from_str;
```

the following might be easier to use (less conditionals) in the source:

```rust
pub(crate) fn json_from_slice<'a, T>(s: &'a mut [u8]) -> Result<T> {
  #[cfg(all(feature = "serde_json", not(feature = "simd-json")))]
  serde_json::from_slice(s)
  #[cfg(feature = "simd-json")]
  simd_json::from_slice(s)
}
pub(crate) fn json_from_str<'a, T>(s: &'a mut str) -> Result<T> {
  #[cfg(all(feature = "serde_json", not(feature = "simd-json")))]
  serde_json::from_str(s)
  #[cfg(feature = "simd-json")]
  simd_json::from_str(s)
}
```

disclaimer: Not tested ;)

**Comment by Licenser** [comment]
Looking at the code a bit more you might be able to return `Option<&mut [u8]>` from `msg()` here https://github.com/twilight-rs/twilight/blob/3aa0548eb15a63eba918a6cde605e93c1c83b62b/gateway/src/shard/processor/inflater.rs#L38 and save yourself a to_vec() call (that said I don't know what side effects that will have to other things :) )

**Comment by dvtkrlbs** [comment]
Thank you so much for the feedback 🤗

**Comment by Licenser** [comment]
I'm glad for people to adopt simd-json :D let me know if you want some more in depth review :)

**Comment by dvtkrlbs** [comment]
I dont want to give you hassle but a problem we have is we log the invalid jsons [here](https://github.com/dvtkrlbs/twilight/blob/6a169bd23641966da15c02555416c8b34eb2ade5/gateway/src/shard/processor/impl.rs#L385) and [here](https://github.com/dvtkrlbs/twilight/blob/6a169bd23641966da15c02555416c8b34eb2ade5/gateway/src/shard/processor/impl.rs#L411) but the problem is we dont want to copy them since we are adding simd-json for squezing every bit of performance we can.

**Comment by Licenser** [comment]
Most of the times (or all I think) :tm: you can just re-use the same input, otherwise it's getting harder. Changes will only happen when the JSON is already validated.

**Comment by dvtkrlbs** [comment]
Oh that is nice to hear. I was worrie that even if the json is not valid it would be still mutated. Thank you ❤️

**Comment by Licenser** [comment]
For completeness in short the algorithm works like this:

It does two passes over the data, in the first one it analyses the structure and if it is valid utf8. If any errors shows  here the data is untouched as its read only. 

The second stage is to parse out the date and here is where changes to content can happen. If a string in the json contains a escape sequence this string will be replaced by its unescaped representation. We can do that because escaped characters are always longer then their unescaped counterparts. So the unescaped result always is shorter and fits within the string. We do it in place because it saves us from having to alocate memory for string (which is a big performance win), but rusts memory modes doesn’t really lend itself to this so we got yo reuse memory the caller owns. 

Now things can still fail in the second stage but only in a few circumstances like invalid numbers or escape sequences. Even then it’s still fine as long as no escaped string was in the json before the error.
