### ISSUE TITLE
Cannot use crate

### ISSUE THREAD

**Issue by benydc** [simd-lite/simd-json#205]
I added the simd-json crate to my project and I cannot build it because of this error:
```
error[E0308]: mismatched types
   --> /Users/.../.cargo/git/checkouts/simd-json-1948e1359b5a8f2a/3a410cc/src/lib.rs:213:86
    |
213 | fn please_compile_with_a_simd_compatible_cpu_setting_read_the_simdjonsrs_readme() -> ! {}
    |    ----------------------------------------------------------------------------      ^ expected `!`, found `()`
    |    |
    |    implicitly returns `()` as its body has no tail or `return` expression
    |
    = note:   expected type `!`
            found unit type `()`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `simd-json`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Can anyone help with this error please?

**Comment by Licenser** [comment]
Hi,
yes that error is there on purpose to make sure that people don't accidentally use `simd-json` without enabling simd and make sure if they do they read the README and do so knowingly.

In short you need to let rust use the right CPU features: https://github.com/simd-lite/simd-json#cpu-target

**Comment by benydc** [comment]
@Licenser thank you!

**Comment by Licenser** [comment]
Awesome :) quite curious, what are you using simd-json for?

**Comment by benydc** [comment]
@Licenser for a high-frequency trading project. I'm still getting some low speeds with this when parsing a websocket json response, as bytes. I have enabled cpu-native and also my CPU is AVX2 capable and even AVX-512. 
I know this project is a port from original, but are the implementations of SIMD instructions same as original or close? 

I want to create my own parser, since I already know the keys, it's same json structure and can also filter not needed bytes.

**Comment by Licenser** [comment]
That's cool! The code is very close to (I believe the last time we checked was 0.3 or 0.4 of upstream `simd json`) doing the comparison is sadly always quite a bit of work since structure between rust and c++ is very different -.-;

There is `simd-json-derive` too if you know the keys and use a struct you can just derive it and it'll do an optimal (or near-optimal) parsing of the tape. Where you could benefit from hand-rolling a parser is if you can short circuit parsing of "uninteresting" data.

It's also worth using the `with_buffers` versions as it avoids allocations :).

Lastly, we found that for extremely small messages simd-json (I can't speak about upstream) is less performant than serde (or possibly other systems) as the overhead to get everything prepared outweighs the performance boost from using simd. So that's worth considering https://github.com/simd-lite/simd-json/issues/198 has some context on that

**Comment by benydc** [comment]
@Licenser in the end I went with serde and borrowed struct, 2 times faster now than simd-json, I get ~300ns per deserialization. I think it can be optimised even further, but for now this is really performant! Thank you!

**Comment by Licenser** [comment]
Awesome :) glad I could help!
