### ISSUE TITLE
Can we assume after calling from_slice the value will be returned to the original value?

### ISSUE THREAD

**Issue by gkorland** [simd-lite/simd-json#267]
The docs of from_slice says "will be rewritten", but can we assume it will rewritten back the original value at the end?

https://github.com/simd-lite/simd-json/blob/e611d9db0116885f66a1683ee1d6f5537b2cd83a/src/serde.rs#L52

**Comment by Licenser** [comment]
Heya, that's probably badly phrased. simd-json uses insitu parsing. When it encounters strings with escape sequences, it will replace them with their utf8-encoded counterparts within the same buffer. "will be rewritten in the process" here is supposed to say: the mut slice you give the function can potentially be altered, don't expect it to be valid anything after the call.

I'm not sure how to reword the docs to make this more clear, do you have a suggestion that would have helped you?

**Comment by Licenser** [comment]
That said, if you have the option and the features provided by it, give simd-json-derive a try as an alternative to serde derive. Where it works it is a decent boost in performance.

**Comment by gkorland** [comment]
I'm using simd-json serde API to create [ijson](https://github.com/Diggsey/ijson).

**Comment by Licenser** [comment]
Just reading through the readme I'm already hooked :D really nice.

It shouldn't be hard to go directly from the tape to the value which will be a lot faster than over the serde interface due to less overhead and no need for the complexity of allowing totally arbitrary constructs.

https://github.com/simd-lite/simd-json/blob/e611d9db0116885f66a1683ee1d6f5537b2cd83a/src/value/owned.rs#L325

is the implementation for simd-json's `Value` you should be able to copy most of that and just adjust it to return the correct type for your i-value.

Also I'm curious would you be up to implement the `value_trait` functions for ivalue, it'd mean being able to have them interoperable with simd-json values :) (happy to help on that front too)

**Comment by utkarshgupta137** [comment]
If I know for a fact that my inputs never have escape sequences, can I assume that the buffer will always stay intact?

**Comment by utkarshgupta137** [comment]
Not really actually. I wanted to benchmark a function, but if I do a clone every time, then it is not accurate. So right now I'm passing the same input every time without cloning.

**Comment by Licenser** [comment]
makes sens, criterion has some solutions for it I think

**Comment by utkarshgupta137** [comment]
I think it is worth mentioning in the doc, even with the caveat that this may not always be true. I don't want to request a feature flag because I have no use for it.

**Comment by utkarshgupta137** [comment]
Would it be possible to guarantee that any changes that simd-json makes today or in the future are "idempotent" i.e. if I pass an input to simd-json & it does some rewriting, passing the rewritten input to simd-json would result in the same output?

**Comment by Licenser** [comment]
no that's impossible, as it invalidates the JSON during mutation
