### ISSUE TITLE
What is the equivalent of the `arbitrary_precision` feature from serde_json?

### ISSUE THREAD

**Issue by utkarshgupta137** [simd-lite/simd-json#297]
What is the equivalent of the [`arbitrary_precision` feature](https://github.com/serde-rs/json/blob/master/Cargo.toml#L72-L78) from serde_json? We want access to the exact (f64) string that was present in the input. We have our own mechanism for parsing decimals from strings & internally representing them in our application. So we'd like access to the original string from the input instead of getting an f64 when we use `Value` from `simd-json`.

Related: https://github.com/Diggsey/ijson/issues/20

**Comment by utkarshgupta137** [comment]
I misunderstood something. I'm able to use `serde_json::Number` directly with simd-json. I don't think there is anything to do here.

**Comment by utkarshgupta137** [comment]
Reopening because I realized this feature is actually required because simd-json first deserializes everything into an internal structure before passing everything to serde's `Deserializer` trait. So what I'm getting from `serde_json::Number` is simd-json parsing into f64 & then converting it back into a `Number`. What I actually want is access to the original string from the message. I think this could be implemented similarly to how serde_json implements `Number` i.e. add a new variant that stores the raw string.

**Comment by Licenser** [comment]
I could see this being achived with  handling the tape-1 to tape-2 transition, not sure how easy it'd be and what the implications are. That said if it's behind a feature flag (or exists side by side) I'd not object to that.

**Comment by utkarshgupta137** [comment]
So I've made a few inroads into adding this feature & it is working for way more tests than I imagined (only 24 are failing with `approx-number-parsing` enabled).
You can see the progress so far here: https://github.com/simd-lite/simd-json/compare/main...utkarshgupta137:simd-json:feat/arbitrary-precision?expand=1

The major problem that I can't figure out is how to create `Node::Number`. This is what I'm doing right now:
```rust
        macro_rules! insert_number {
            ($negative: literal) => {
                #[cfg(feature = "arbitrary-precision")]
                // FIXME: This should be derived from input2
                insert_res!(Node::Number(&input[idx..]));
                #[cfg(not(feature = "arbitrary-precision"))]
                insert_res!(Node::Static(s2try!(Self::parse_number(
                    idx, input2, $negative
                ))));
            };
        }
```
Just taking it from input causes all escaped-string related tests to fail. It also causes index out of bounds in a lot of tests. Ideally we'll want to take it from `input2`, but that doesn't live long enough. I can't clone it either, because then I can't store it in `Node` (which needs to be `Copy`).
Based on your comments - as of now at least, we shouldn't have to rewrite any of the numerical parts of the input. So is there a way to get the correct `idx` to use with `input`?

The 2nd problem is that the parser sometimes tries to peek into the next character, when there isn't any. Normally it won't matter because `AlignedBuf` has the padding, but in our case, for simple inputs like `0`, it is failing. One solution for this could be to readd a check & fallback to 0 when this feature is enabled inside `parse_number`. Or we could even add a generic to it so that the fallback is only present when calling from `number.rs`.

**Comment by Licenser** [comment]
Sorry for the late reply,

First, to your question, look at `insert_str!` to see how to borrow data from the original index. and again you *can not* rely on the input remaining unchanged, this is a invalid assumption!

A few things I noticed while reviewing your code:

## `PartialEq`

The implementation for `*Number` is quite incorrect, since they're numbers even so not yet parsed equivalence needs to be handled on a numeric level `-0` and `0` for example are equal. as well as different ways to write floats.

## `next_static`

adds function calls even w/o the feature flag. The compiler should smart enough to compile that out but that should be verified.

## `visit_static_node`

adds a function call and a nested match, I think this should be rewritten to retain the original match and only nest inside `Node::Number`




if it adds branches to the non modified code that's needs to be refactored to avoid that, the feature flag should not degrade performance unless it is set

**Comment by Licenser** [comment]
I'll close this issue since it is mostly answered and the rest is more correctly captured in #82
