### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [simd-lite/simd-json#352]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/simd-lite/simd-json/assets/147402107/d9fbf057-3b8a-45d8-9e08-c676b1320fc4)

**Comment by Kalyanimhala** [comment]
@Licenser Kindly assign me this issue, I want to work on it.

**Comment by Licenser** [comment]
Hi Kalyan, I agree that contributors are the core of any community but I'm a bit wary about adding a list to the readme.

So a few questions: 
- would you imagine the list to be automatically updated or maintained manually? 
- what benefit does it have over the contributor graph already existing in github?
- Since the readme is part of the documentation how will this impact the usability of the [docs](https://docs.rs/simd-json/latest/simd_json/)? Having a long list in there of people will make the documentation harder to use.

**Comment by Kalyanimhala** [comment]
- Yeah, It will updated automatically!
- It will helps to the new contributors who want to contributed in the project. because, its encouraging everyone to be part of project and and before contributing in any project, every user firstly reads the Readme.md file.
- At the end of Readme, we can add a special section there!
@Licenser Thanks for asking !!

**Comment by Licenser** [comment]
If it doesn't require manual updates my main concern with it is alleviated :) lets give it a try, we can take a look on how it affects the docs and if it hinders readability once we see it 👍
