### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by yonas** [simd-lite/simd-json#368]
Could you please publish benchmarks against [sonic-rs](https://github.com/cloudwego/sonic-rs) and [simd-json](https://github.com/simdjson/simdjson)?

Here's an example: https://github.com/cloudwego/sonic-rs?tab=readme-ov-file#benchmark

**Comment by Licenser** [comment]
instead of duplicating the issue I opted for contributing to an existing benchmark suite: https://github.com/serde-rs/json-benchmark ; it's not the most up to date simd-json since https://github.com/serde-rs/json-benchmark/issues/14 hasn't been merged but I don't think making another suite is going to be useful.

**Comment by yonas** [comment]
Ah, ok, thanks!

Hopefully they'll update the project link #25
