### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simd-json#57]
We still have a rather low test coverage on parts of the code (my fault -.-) now that we can measure it we should aim to improve it. 90%+ sounds like a good target

**Comment by sunnygleason** [comment]
Yay! You found my not-so-subtle reason for adding coverage 😂

**Comment by Licenser** [comment]
To be fair the coverage of the critical path is quite good, >90% even with the buggy coverage. The tests missing are more for 'boring/unimporant' functions and will just exist to push the number and make it look nicer.

**Comment by sunnygleason** [comment]
👍 , my 100% coverage club membership expired a couple years ago... 😂

**Comment by Licenser** [comment]
I have lots of opinions on the topic 😂

**Comment by sunnygleason** [comment]
getting there! the big thing that jumps out at me here are:

* [ ] serde
* [ ] stage2.rs

Wondering if there's a way to get the macros out of the function definition in `stage2.rs` ...

**Comment by Licenser** [comment]
Ja serde is the big thing left.

**Comment by dvermd** [comment]
I think there's some dead code in the serde part of this crate. Can you help identify if this is correct ?

1. In `serde/value/owned/se.rs`, I didn't manage to trigger any function of `MapKeySerializer` other than `serialize_str`. I think this is because, internally, the Object type of a Value is a `HashMap<String, Value>` and thus, only String keys will be serialized
2. In `serde/value/owned/de.rs`, the `ValueVisitor::visit_i/u 8/16/32` should be called from the `parse_integer` from serde_json but it only ever returns a i64, a u64 or a f64 as of https://github.com/serde-rs/json/blob/master/src/de.rs#L380.
3. Same for the borrowed values

**Comment by Licenser** [comment]
We have a lot of tests now
